version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    restart: always
    volumes:
      - ./var/docker/artifacts:/usr/local/sbin
      # - ./web/dist:/app/web/dist
    ports:
      - 8000:8080
    command: "/usr/local/sbin/server"
  ui:
    image: library/node:14
    volumes:
      - ./web:/app
    working_dir: /app
    restart: always
    command: "npm run start"

  proxy:
    image: library/nginx:1.19
    volumes:
      - ./docker/proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: always
    depends_on:
      - ui
      - api

  # db:
  #   image: library/mariadb:10
  #   volumes:
  #     - ./docker/dbinit:/docker-entrypoint-initdb.d
  #     - ./var/db/data:/var/lib/mysql
  #   env_file: .env
  #   ports:
  #     - 3308:3306
  #   environment:
  #     MYSQL_RANDOM_ROOT_PASSWORD: 1
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: ${DB_DATABASE}
